function createfigure(X1, Y1, Y2, Y3, Y4, Y5, Y6)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4, Y5, Y6)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data
%  Y6:  vector of y data

%  Auto-generated by MATLAB on 10-Apr-2022 13:39:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.1425 0.7975 0.7625 0.1275]);
hold(axes1,'on');

% Create datetime plot
plot(X1,Y1,'Parent',axes1,...
    'MarkerFaceColor',[0.600000023841858 0.800000011920929 1],...
    'MarkerEdgeColor',[0 0.200000002980232 1],...
    'MarkerSize',8,...
    'Marker','o',...
    'LineWidth',2,...
    'Color',[0.200000002980232 0.200000002980232 1]);

% Create ylabel
ylabel('Column 1','HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Rotation',0);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[723134.633224043 735703.693224043]);
% Create axes
axes2 = axes('Parent',figure1,'Position',[0.1425 0.66 0.7625 0.1275]);
hold(axes2,'on');

% Create datetime plot
plot(X1,Y2,'Parent',axes2);

% Create ylabel
ylabel('Accumulation (mm w.e.)','HorizontalAlignment','right',...
    'Rotation',-90,...
    'VerticalAlignment','middle');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[723134.633224043 735703.693224043]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[3764.31973582443 5496.80697804626]);
% Set the remaining axes properties
set(axes2,'YAxisLocation','right');
% Create axes
axes3 = axes('Parent',figure1,'Position',[0.1425 0.5225 0.7625 0.1275]);
hold(axes3,'on');

% Create datetime plot
plot(X1,Y3,'Parent',axes3);

% Create ylabel
ylabel('Column 3','HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Rotation',0);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[723134.633224043 735703.693224043]);
% Create axes
axes4 = axes('Parent',figure1,'Position',[0.1425 0.385 0.7625 0.1275]);
hold(axes4,'on');

% Create datetime plot
plot(X1,Y4,'Parent',axes4);

% Create ylabel
ylabel('Column 4','HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Rotation',0);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[723134.633224043 735703.693224043]);
% Create axes
axes5 = axes('Parent',figure1,'Position',[0.1425 0.2475 0.7625 0.1275]);
hold(axes5,'on');

% Create datetime plot
plot(X1,Y5,'Parent',axes5);

% Create ylabel
ylabel('Column 5','HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Rotation',0);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[723134.633224043 735703.693224043]);
% Create axes
axes6 = axes('Parent',figure1,'Position',[0.1425 0.11 0.7625 0.1275]);
hold(axes6,'on');

% Create datetime plot
plot(X1,Y6,'Parent',axes6);

% Create ylabel
ylabel('Column 6','HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Rotation',0);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[723134.633224043 735703.693224043]);
% Create line
annotation(figure1,'line',[0.320833333333333 0.320833333333333],...
    [0.11 0.925],'PickableParts','none','Visible','off','Color',[0 0.6 1],...
    'LineWidth',1.5);

% Create textbox
annotation(figure1,'textbox',...
    [0.320833333333333 0.925 0.0310763888888889 0.0180115273775217],...
    'PickableParts','none',...
    'Visible','off',...
    'Color',[0 0.6 1],...
    'VerticalAlignment','bottom',...
    'String','723166',...
    'Margin',1,...
    'LineStyle','none',...
    'FontWeight','bold',...
    'BackgroundColor',[0.94 0.94 0.94]);

